retall

;***************SPECIFY THE DISK AREA FOR THE OUTPUT FILES ***********
outpath = '/share/heiles/newcal/testout/output/'
;cumcorr= 0

;----lb2-------------
tcalxx_board = - [1.76, 1.80,1.82,1.81]
tcalyy_board = - [2.01, 1.96, 1.94, 1.95]
; inp direct for datafile
corpath= '/share/olcor/'
;

;------------------
;corfilename= corpath + 'corfile.11oct02.a1158.1'

corfile= 'corfile.11oct02.a1158.1'


