@tstm2_setup.idl

;READ THE INPUT FILE...
mm2_read, pathin, inputfilename, sourcename, rcvr_name, $
        hb_arr, a, beamin_arr, beamout_arr, $
        indx

;DEFINE PLOTTING OPTIONSB...
plt0yes= 1
plt1yes= 1
ps1yes= 0
check= 0
chnl=1
saveit=1
m7=0

;PROCESS THE DATA...WRITE THE OUTPUT...
mm4, path, inputfilename, muellerparams_init, $
	indx, hb_arr, a, beamin_arr, beamout_arr, $
        muellerparam1, $
	plt0yes=plt0yes, plt1yes=plt1yes, ps1yes=ps1yes, $
	check=check, chnl=chnl, saveit=saveit, m7=m7
